version: "3.8"
name: app
services:
  reverse-proxy-nginx:
    container_name: reverse-proxy-nginx
    image: nginx:stable-alpine
    depends_on:
      - mongo
      - api
    volumes:
      - ./.nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - backend


  mongo:
    container_name: mongo
    image: mongo:jammy
    networks:
      - backend
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  api:
    restart: on-failure
    container_name: api
    build: ./api/
    depends_on:
      - mongo
    networks:
      - backend

    environment:
      MONGO_URL: mongodb://admin:admin@mongo:27017
      API_ROOT_PATH: "/api"


  frontend:
    container_name: frontend
    build: 
      context: ./frontend/
      dockerfile: Dockerfile
      target: prod
    depends_on:
      - reverse-proxy-nginx
    networks:
      - backend


networks:
  backend:
    driver: bridge

